### ISSUE TITLE
Issue with Login (user name,password)

### ISSUE THREAD

**Issue by ChillSpike-zz** [mightyjava/springboot-jsp-bootstrap#1]
Hi @mightyjava  ,
I have deployed the application and created a table  "**user** " with the following value being inserted 

`insert into user (user_id,user_name,password,id,email,full_name,mobile,role_id) values ('user_1','test user','test@123',1,'test.user@spring.com','test user1','9871237642','44');
`
When I log into : http://localhost:8084/mightyjava/user/login 
with the credentials _test user_ and _test@123_ , the login fails .

Could you please clarify on the data-set to login

**Comment by mightyjava** [comment]
Password must be encrypted - 
Replace 'test@123' -> '$2a$10$41qTWvhlE0cKxBWX1RsMLeA9dsWcSzgGPziTKLVBptivQ5Hmu.Pym'

encrypted password nothing but - 'password'

**Comment by ChillSpike** [comment]
@mightyjava  
Thank you very much for the response ,
Is it a bcrypt password ?
Could you provide the hash  ?
the "password works fine for "test user" but if I use "$2a$10$41qTWvhlE0cKxBWX1RsMLeA9dsWcSzgGPziTKLVBptivQ5Hmu.Pym" for "admin" it does not work
